import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { SavedJobsProvider } from "@/context/SavedJobsContext";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import StoreProvider from "./providers/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Health Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <SavedJobsProvider>
          <StoreProvider>
            <AntdRegistry>
              <Suspense>
                <Navbar />
                <div className="  md:min-h-[calc(100vh-180px)]">
                  {children}
                </div>

                <Footer />
              </Suspense>
            </AntdRegistry>
          </StoreProvider>
        </SavedJobsProvider>
      </body>
    </html>
  );
}
